# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: employee.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'employee.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\x08\x65mployee\".\n\x17ValidateEmployeeRequest\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\t\"F\n\x18ValidateEmployeeResponse\x12\x13\n\x0b\x65mployee_id\x18\x01 \x01(\t\x12\x15\n\remployee_name\x18\x02 \x01(\t2l\n\x0f\x45mployeeService\x12Y\n\x10ValidateEmployee\x12!.employee.ValidateEmployeeRequest\x1a\".employee.ValidateEmployeeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEEMPLOYEEREQUEST']._serialized_start=28
  _globals['_VALIDATEEMPLOYEEREQUEST']._serialized_end=74
  _globals['_VALIDATEEMPLOYEERESPONSE']._serialized_start=76
  _globals['_VALIDATEEMPLOYEERESPONSE']._serialized_end=146
  _globals['_EMPLOYEESERVICE']._serialized_start=148
  _globals['_EMPLOYEESERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
