# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import auth_service_pb2 as auth__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Auth/User Service for validating and fetching user/employee data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateUser = channel.unary_unary(
                '/auth.AuthService/ValidateUser',
                request_serializer=auth__service__pb2.ValidateUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/auth.AuthService/GetUser',
                request_serializer=auth__service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=auth__service__pb2.User.FromString,
                _registered_method=True)
        self.GetUsers = channel.unary_unary(
                '/auth.AuthService/GetUsers',
                request_serializer=auth__service__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=auth__service__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.ValidateEmployee = channel.unary_unary(
                '/auth.AuthService/ValidateEmployee',
                request_serializer=auth__service__pb2.ValidateEmployeeRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateEmployeeResponse.FromString,
                _registered_method=True)
        self.GetEmployee = channel.unary_unary(
                '/auth.AuthService/GetEmployee',
                request_serializer=auth__service__pb2.GetEmployeeRequest.SerializeToString,
                response_deserializer=auth__service__pb2.Employee.FromString,
                _registered_method=True)
        self.ValidateBranch = channel.unary_unary(
                '/auth.AuthService/ValidateBranch',
                request_serializer=auth__service__pb2.ValidateBranchRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateBranchResponse.FromString,
                _registered_method=True)
        self.GetBranch = channel.unary_unary(
                '/auth.AuthService/GetBranch',
                request_serializer=auth__service__pb2.GetBranchRequest.SerializeToString,
                response_deserializer=auth__service__pb2.Branch.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Auth/User Service for validating and fetching user/employee data
    """

    def ValidateUser(self, request, context):
        """Validate if a user/employee exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get user/employee details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Get multiple users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateEmployee(self, request, context):
        """Validate employee ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmployee(self, request, context):
        """Get employee details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateBranch(self, request, context):
        """Validate branch ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBranch(self, request, context):
        """Get branch details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateUser,
                    request_deserializer=auth__service__pb2.ValidateUserRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=auth__service__pb2.GetUserRequest.FromString,
                    response_serializer=auth__service__pb2.User.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=auth__service__pb2.GetUsersRequest.FromString,
                    response_serializer=auth__service__pb2.GetUsersResponse.SerializeToString,
            ),
            'ValidateEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateEmployee,
                    request_deserializer=auth__service__pb2.ValidateEmployeeRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateEmployeeResponse.SerializeToString,
            ),
            'GetEmployee': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmployee,
                    request_deserializer=auth__service__pb2.GetEmployeeRequest.FromString,
                    response_serializer=auth__service__pb2.Employee.SerializeToString,
            ),
            'ValidateBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateBranch,
                    request_deserializer=auth__service__pb2.ValidateBranchRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateBranchResponse.SerializeToString,
            ),
            'GetBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBranch,
                    request_deserializer=auth__service__pb2.GetBranchRequest.FromString,
                    response_serializer=auth__service__pb2.Branch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Auth/User Service for validating and fetching user/employee data
    """

    @staticmethod
    def ValidateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateUser',
            auth__service__pb2.ValidateUserRequest.SerializeToString,
            auth__service__pb2.ValidateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUser',
            auth__service__pb2.GetUserRequest.SerializeToString,
            auth__service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetUsers',
            auth__service__pb2.GetUsersRequest.SerializeToString,
            auth__service__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateEmployee',
            auth__service__pb2.ValidateEmployeeRequest.SerializeToString,
            auth__service__pb2.ValidateEmployeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmployee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetEmployee',
            auth__service__pb2.GetEmployeeRequest.SerializeToString,
            auth__service__pb2.Employee.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/ValidateBranch',
            auth__service__pb2.ValidateBranchRequest.SerializeToString,
            auth__service__pb2.ValidateBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthService/GetBranch',
            auth__service__pb2.GetBranchRequest.SerializeToString,
            auth__service__pb2.Branch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
