# Generated by Django 5.2.6 on 2025-11-28 10:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Screening", "Screening"),
                            ("Interview", "Interview"),
                            ("Offered", "Offered"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Applied",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In Review", "In Review"),
                            ("Shortlisted", "Shortlisted"),
                            ("Hired", "Hired"),
                            ("Rejected", "Rejected"),
                        ],
                        default="New",
                        max_length=50,
                    ),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("cover_letter", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to="hr.jobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant",
                "verbose_name_plural": "Applicants",
                "db_table": "applicants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application_id"], name="applicants_applica_7979f2_idx"
                    ),
                    models.Index(fields=["email"], name="applicants_email_323aeb_idx"),
                    models.Index(fields=["stage"], name="applicants_stage_22f50e_idx"),
                    models.Index(
                        fields=["status"], name="applicants_status_c99fa2_idx"
                    ),
                ],
            },
        ),
    ]
