# Generated by Django 5.2.6 on 2025-12-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_applicant"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_id", models.CharField(db_index=True, max_length=50)),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "employee_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("Sick Leave", "Sick Leave"),
                            ("Annual Leave", "Annual Leave"),
                            ("Casual Leave", "Casual Leave"),
                            ("Maternity Leave", "Maternity Leave"),
                            ("Paternity Leave", "Paternity Leave"),
                            ("Unpaid Leave", "Unpaid Leave"),
                            ("Compassionate Leave", "Compassionate Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("approver_id", models.CharField(blank=True, max_length=50, null=True)),
                ("approval_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee_id", "status"],
                        name="leave_reque_employe_fd03a1_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="leave_reque_start_d_08703b_idx",
                    ),
                ],
            },
        ),
    ]
