# Generated by Django 5.2.6 on 2025-12-01 15:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_leaverequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_id", models.CharField(db_index=True, max_length=50)),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "employee_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "payroll_period",
                    models.CharField(
                        help_text="e.g., July 2025, Q1 2025, etc.", max_length=50
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "allowances",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Allowances breakdown as key-value pairs",
                    ),
                ),
                (
                    "deductions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Deductions breakdown as key-value pairs",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("disbursement_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Paid", "Paid"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payroll Records",
                "db_table": "payroll",
                "ordering": ["-disbursement_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee_id", "payroll_period"],
                        name="payroll_employe_87d660_idx",
                    ),
                    models.Index(
                        fields=["disbursement_date"], name="payroll_disburs_20cb89_idx"
                    ),
                    models.Index(fields=["status"], name="payroll_status_ac0f6a_idx"),
                ],
                "unique_together": {("employee_id", "payroll_period")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_id", models.CharField(db_index=True, max_length=50)),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "employee_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                ("reviewer_id", models.CharField(db_index=True, max_length=50)),
                ("reviewer_name", models.CharField(max_length=255)),
                ("review_date", models.DateField()),
                (
                    "review_period",
                    models.CharField(
                        help_text="e.g., Q1 2025, H1 2025, 2025, etc.", max_length=50
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        help_text="Employee's key strengths and accomplishments"
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.TextField(help_text="Areas where the employee can improve"),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Additional feedback and comments",
                        null=True,
                    ),
                ),
                (
                    "goals_met",
                    models.BooleanField(
                        default=True, help_text="Whether the employee met their goals"
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True,
                        help_text="Scheduled date for next review",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Review",
                "verbose_name_plural": "Performance Reviews",
                "db_table": "performance_reviews",
                "ordering": ["-review_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee_id", "review_date"],
                        name="performance_employe_90c87e_idx",
                    ),
                    models.Index(
                        fields=["reviewer_id", "review_date"],
                        name="performance_reviewe_0be9ca_idx",
                    ),
                    models.Index(
                        fields=["review_period"], name="performance_review__395498_idx"
                    ),
                ],
                "unique_together": {("employee_id", "review_period")},
            },
        ),
    ]
