# Generated by Django 5.2.6 on 2025-12-01 15:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0004_payroll_performancereview"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_name", models.CharField(db_index=True, max_length=255)),
                (
                    "provider",
                    models.CharField(
                        help_text="Training provider or organization", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the training program"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost of the training program",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("All Employees", "All Employees"),
                            ("Management", "Management"),
                            ("New Hires", "New Hires"),
                            ("Department Specific", "Department Specific"),
                            ("Leadership Team", "Leadership Team"),
                            ("Technical Staff", "Technical Staff"),
                            ("Sales Team", "Sales Team"),
                            ("Customer Service", "Customer Service"),
                        ],
                        default="All Employees",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Program",
                "verbose_name_plural": "Training Programs",
                "db_table": "training_programs",
                "ordering": ["-start_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program_name", "start_date"],
                        name="training_pr_program_110536_idx",
                    ),
                    models.Index(
                        fields=["status", "start_date"],
                        name="training_pr_status_e87c18_idx",
                    ),
                    models.Index(
                        fields=["target_audience"],
                        name="training_pr_target__b419b2_idx",
                    ),
                ],
            },
        ),
    ]
