# Generated by Django 5.2.6 on 2025-12-01 16:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_trainingprogram"),
    ]

    operations = [
        migrations.CreateModel(
            name="Associate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "associate_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated associate ID (e.g., ASC-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=255)),
                ("phone_number", models.CharField(max_length=50)),
                ("address", models.TextField(blank=True, null=True)),
                ("company_name", models.CharField(db_index=True, max_length=255)),
                (
                    "role_position",
                    models.CharField(
                        choices=[
                            ("IT Consultant", "IT Consultant"),
                            ("UX Designer", "UX Designer"),
                            ("Legal Advisor", "Legal Advisor"),
                            ("Marketing Specialist", "Marketing Specialist"),
                            ("Financial Analyst", "Financial Analyst"),
                            ("HR Consultant", "HR Consultant"),
                            ("Software Developer", "Software Developer"),
                            ("Project Manager", "Project Manager"),
                            ("Security Consultant", "Security Consultant"),
                            ("Business Analyst", "Business Analyst"),
                            ("Data Analyst", "Data Analyst"),
                            ("Content Writer", "Content Writer"),
                            ("Graphic Designer", "Graphic Designer"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=100,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Area of specialization or expertise",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("contract_start_date", models.DateField()),
                ("contract_end_date", models.DateField()),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total value of the contract",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Milestone-based", "Milestone-based"),
                            ("One-time", "One-time"),
                            ("Hourly", "Hourly"),
                            ("Project-based", "Project-based"),
                        ],
                        default="Monthly",
                        max_length=50,
                    ),
                ),
                (
                    "supervisor_point_of_contact",
                    models.CharField(
                        blank=True,
                        help_text="Internal supervisor or point of contact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scope_of_work",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of work scope",
                        null=True,
                    ),
                ),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        help_text="Upload contract, resume, or relevant documents",
                        null=True,
                        upload_to="associates/documents/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Expired", "Expired"),
                            ("Terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="associates",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Associate",
                "verbose_name_plural": "Associates",
                "db_table": "associates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["associate_id"], name="associates_associa_3394dc_idx"
                    ),
                    models.Index(
                        fields=["email", "status"], name="associates_email_3d6cf9_idx"
                    ),
                    models.Index(
                        fields=["company_name", "role_position"],
                        name="associates_company_6f8a4d_idx",
                    ),
                    models.Index(
                        fields=["contract_start_date", "contract_end_date"],
                        name="associates_contrac_aef6e7_idx",
                    ),
                ],
            },
        ),
    ]
