# Generated by Django 5.2.6 on 2025-12-02 12:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_associate"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWorkReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_name", models.CharField(db_index=True, max_length=255)),
                ("employee_email", models.EmailField(db_index=True, max_length=255)),
                ("date", models.DateField(db_index=True)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        help_text="Total hours worked for the day",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("Happy", "Happy"),
                            ("Neutral", "Neutral"),
                            ("Sad", "Sad"),
                            ("Stressed", "Stressed"),
                            ("Tired", "Tired"),
                        ],
                        default="Neutral",
                        max_length=20,
                    ),
                ),
                (
                    "challenges",
                    models.TextField(
                        blank=True, help_text="Challenges faced today", null=True
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Accomplishments today", null=True
                    ),
                ),
                (
                    "plan_next_day",
                    models.TextField(
                        blank=True, help_text="Plan for tomorrow", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Work Report",
                "verbose_name_plural": "Daily Work Reports",
                "db_table": "daily_work_reports",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee_email", "date"],
                        name="daily_work__employe_fc8060_idx",
                    ),
                    models.Index(
                        fields=["status"], name="daily_work__status_15865d_idx"
                    ),
                ],
                "unique_together": {("employee_email", "date")},
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique Asset ID (e.g., AST-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the asset", max_length=255),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("Laptop", "Laptop"),
                            ("Printer", "Printer"),
                            ("Vehicle", "Vehicle"),
                            ("Furniture", "Furniture"),
                            ("Equipment", "Equipment"),
                            ("Other", "Other"),
                        ],
                        default="Equipment",
                        max_length=50,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "branch",
                    models.CharField(
                        help_text="Branch where the asset is located", max_length=100
                    ),
                ),
                (
                    "assigned_to_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the person assigned to",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "assigned_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the person assigned to",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Use", "In Use"),
                            ("Maintenance", "Maintenance"),
                            ("Available", "Available"),
                            ("Retired", "Retired"),
                            ("Lost/Stolen", "Lost/Stolen"),
                        ],
                        db_index=True,
                        default="Available",
                        max_length=50,
                    ),
                ),
                ("warranty_expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "documents",
                    models.FileField(
                        blank=True,
                        help_text="Upload invoice, warranty, manual, etc.",
                        null=True,
                        upload_to="assets/documents/",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["asset_id"], name="assets_asset_i_6c35ce_idx"),
                    models.Index(fields=["status"], name="assets_status_326766_idx"),
                    models.Index(
                        fields=["asset_type"], name="assets_asset_t_fc4c39_idx"
                    ),
                    models.Index(fields=["branch"], name="assets_branch_6d5ad5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Scorecard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.DateField(
                        help_text="The month this scorecard represents (stored as first day of month)"
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall score out of 100",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "target_achievement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target achievement percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "branch_ranking",
                    models.IntegerField(
                        help_text="Ranking within the branch for the month"
                    ),
                ),
                (
                    "skill_update_progress",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Skill update progress percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "attendance_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Attendance score percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "task_delivery_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Task delivery score percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "report_accuracy_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Report accuracy score percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "brand_contribution_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Brand contribution score percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "training_progress_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Training progress score percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "associate",
                    models.ForeignKey(
                        help_text="Associate this scorecard belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="hr.associate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scorecard",
                "verbose_name_plural": "Scorecards",
                "db_table": "scorecards",
                "ordering": ["-month", "-overall_score"],
                "indexes": [
                    models.Index(fields=["month"], name="scorecards_month_e42464_idx"),
                    models.Index(
                        fields=["associate", "month"],
                        name="scorecards_associa_ccc16c_idx",
                    ),
                ],
                "unique_together": {("associate", "month")},
            },
        ),
    ]
