# Generated by Django 5.2.6 on 2025-12-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_dailyworkreport_asset_scorecard"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the award (e.g., Employee of the Month)",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Category of the award (e.g., Monthly Recognition, Excellence)",
                        max_length=100,
                    ),
                ),
                (
                    "date_awarded",
                    models.DateField(help_text="Date the award was given"),
                ),
                (
                    "rank_level",
                    models.CharField(
                        help_text="Rank or level of the award (e.g., Enugu State, Headquarters)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or reason for the award",
                        null=True,
                    ),
                ),
                (
                    "associate",
                    models.ForeignKey(
                        help_text="Associate receiving the award",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="hr.associate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Award",
                "verbose_name_plural": "Awards",
                "db_table": "awards",
                "ordering": ["-date_awarded"],
                "indexes": [
                    models.Index(
                        fields=["date_awarded"], name="awards_date_aw_4afe15_idx"
                    ),
                    models.Index(
                        fields=["associate", "date_awarded"],
                        name="awards_associa_cb746f_idx",
                    ),
                    models.Index(fields=["category"], name="awards_categor_61f28d_idx"),
                ],
            },
        ),
    ]
