# Generated by Django 5.2.6 on 2025-12-02 15:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_award"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.DateField(
                        help_text="The month this ranking represents (stored as first day of month)"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Performance score for the month",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(help_text="Rank position in the leaderboard"),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Performance status label (e.g., Rising Star, Consistent Performer)",
                        max_length=100,
                    ),
                ),
                (
                    "awards_summary",
                    models.TextField(
                        blank=True,
                        help_text="Snapshot of awards received this month",
                        null=True,
                    ),
                ),
                (
                    "associate",
                    models.ForeignKey(
                        help_text="Associate in the leaderboard",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="hr.associate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Leaderboard Entry",
                "verbose_name_plural": "Performance Leaderboard Entries",
                "db_table": "performance_leaderboard",
                "ordering": ["-month", "rank"],
                "indexes": [
                    models.Index(fields=["month"], name="performance_month_adc009_idx"),
                    models.Index(
                        fields=["month", "rank"], name="performance_month_8c6ab8_idx"
                    ),
                ],
                "unique_together": {("associate", "month")},
            },
        ),
    ]
