# Generated by Django 5.2.6 on 2025-12-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_performanceleaderboard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyworkreport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="dailyworkreport",
            name="employee_id",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Employee ID from main backend",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyworkreport",
            unique_together={("employee_id", "date")},
        ),
        migrations.AddIndex(
            model_name="dailyworkreport",
            index=models.Index(
                fields=["employee_id", "date"], name="daily_work__employe_ba303d_idx"
            ),
        ),
    ]
