# Generated by Django 5.2.6 on 2025-12-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_alter_dailyworkreport_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="assigned_to_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Employee ID from main auth service",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="assigned_to_email",
            field=models.EmailField(
                blank=True,
                help_text="Cached email of the person assigned to",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="assigned_to_name",
            field=models.CharField(
                blank=True,
                help_text="Cached name of the person assigned to",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["assigned_to_id"], name="assets_assigne_36a4dc_idx"
            ),
        ),
    ]
