# Generated by Django 5.2.6 on 2026-01-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_asset_assigned_to_id_alter_asset_assigned_to_email_and_more"),
    ]

    operations = [
        # Delete SubDepartment model first (it references Department)
        migrations.DeleteModel(
            name="SubDepartment",
        ),
        # Remove department ForeignKey from existing models
        migrations.RemoveField(
            model_name="asset",
            name="department",
        ),
        migrations.RemoveField(
            model_name="associate",
            name="department",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="department",
        ),
        # Add department_id CharField to models
        migrations.AddField(
            model_name="asset",
            name="department_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Department ID from department microservice",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="associate",
            name="department_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Department ID from department microservice",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="department_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Department ID from department microservice",
                max_length=255,
                null=True,
            ),
        ),
        # Delete Department model last
        migrations.DeleteModel(
            name="Department",
        ),
    ]
