# Generated by Django 5.2.6 on 2026-01-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_remove_asset_department_remove_associate_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobposting",
            old_name="location",
            new_name="branch_id",
        ),
    ]
