# Generated by Django 5.2.6 on 2026-01-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_rename_location_jobposting_branch_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="applicant",
            name="applicants_applica_7979f2_idx",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="application_id",
        ),
        migrations.AddField(
            model_name="applicant",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="portolio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="cover_letter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="resume",
            field=models.URLField(blank=True, null=True),
        ),
    ]
