# Generated by Django 5.2.6 on 2026-01-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_remove_applicant_applicants_applica_7979f2_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverequest",
            name="employee_email",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="employee_name",
        ),
    ]
