# Generated by Django 5.2.6 on 2026-01-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0015_remove_leaverequest_employee_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="performancereview",
            name="employee_email",
        ),
        migrations.RemoveField(
            model_name="performancereview",
            name="employee_name",
        ),
        migrations.RemoveField(
            model_name="performancereview",
            name="goals_met",
        ),
        migrations.RemoveField(
            model_name="performancereview",
            name="next_review_date",
        ),
        migrations.RemoveField(
            model_name="performancereview",
            name="reviewer_name",
        ),
        migrations.AddField(
            model_name="performancereview",
            name="employee_comment",
            field=models.TextField(
                blank=True, help_text="Additional feedback and comments", null=True
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="review_period",
            field=models.CharField(
                choices=[("q1", "Q1"), ("q2", "Q2"), ("q3", "Q3"), ("q4", "Q4")],
                help_text="e.g., Q1 2025, H1 2025, 2025, etc.",
                max_length=50,
            ),
        ),
    ]
