# Generated by Django 5.2.6 on 2026-01-15 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0016_remove_performancereview_employee_email_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asset",
            name="assets_asset_i_6c35ce_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailyworkreport",
            name="daily_work__employe_fc8060_idx",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="asset_id",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="assigned_to_email",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="assigned_to_name",
        ),
        migrations.RemoveField(
            model_name="dailyworkreport",
            name="employee_email",
        ),
        migrations.RemoveField(
            model_name="dailyworkreport",
            name="employee_name",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="employee_email",
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="employee_name",
        ),
        migrations.AddField(
            model_name="dailyworkreport",
            name="feedback",
            field=models.TextField(blank=True, help_text="Feedback", null=True),
        ),
        migrations.AddField(
            model_name="dailyworkreport",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="documents",
            field=models.URLField(
                blank=True,
                help_text="Upload invoice, warranty, manual, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dailyworkreport",
            name="mood",
            field=models.CharField(
                choices=[
                    ("Happy", "Happy"),
                    ("Neutral", "Neutral"),
                    ("Sad", "Sad"),
                    ("Stressed", "Stressed"),
                    ("Tired", "Tired"),
                    ("Frustrated", "Frustrated"),
                ],
                default="Neutral",
                max_length=20,
            ),
        ),
    ]
