# Generated by Django 5.2.6 on 2026-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_remove_asset_assets_asset_i_6c35ce_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyworkreport",
            options={
                "ordering": ["-day", "-created_at"],
                "verbose_name": "Daily Work Report",
                "verbose_name_plural": "Daily Work Reports",
            },
        ),
        migrations.RemoveIndex(
            model_name="dailyworkreport",
            name="daily_work__employe_ba303d_idx",
        ),
        migrations.RenameField(
            model_name="dailyworkreport",
            old_name="date",
            new_name="day",
        ),
        migrations.AlterUniqueTogether(
            name="dailyworkreport",
            unique_together={("employee_id", "day")},
        ),
        migrations.AddIndex(
            model_name="dailyworkreport",
            index=models.Index(
                fields=["employee_id", "day"], name="daily_work__employe_4c3bd3_idx"
            ),
        ),
    ]
