# Generated by Django 5.2.6 on 2026-01-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_alter_dailyworkreport_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performanceleaderboard",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="performanceleaderboard",
            name="associate",
        ),
        migrations.AlterUniqueTogether(
            name="scorecard",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="scorecard",
            name="associate",
        ),
        migrations.RemoveIndex(
            model_name="award",
            name="awards_associa_cb746f_idx",
        ),
        migrations.RemoveField(
            model_name="award",
            name="associate",
        ),
        migrations.AlterField(
            model_name="award",
            name="category",
            field=models.CharField(
                choices=[
                    ("employee_of_the_month", "Employee of the month"),
                    ("state_excellence_winner", "State excellence winner"),
                    ("best_branch_representative", "Best branch representative"),
                    ("regional_leader", "Regional leader"),
                    ("dependable_team_member", "Dependable team member"),
                    ("Other", "Other"),
                ],
                help_text="Category of the award (e.g., Monthly Recognition, Excellence)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="award",
            name="rank_level",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("state", "State"),
                    ("inter-state-region", "Inter state region"),
                    ("national", "National"),
                ],
                help_text="Rank or level of the award (e.g., Enugu State, Headquarters)",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="PerformanceLeaderboard",
        ),
        migrations.DeleteModel(
            name="Scorecard",
        ),
    ]
