# Generated by Django 5.2.6 on 2026-01-15 14:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0019_alter_performanceleaderboard_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisciplinaryCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Employee ID or identifier", max_length=100
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True,
                        help_text="Employee full name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("Verbal Warning", "Verbal Warning"),
                            ("Written Warning", "Written Warning"),
                            ("Suspension", "Suspension"),
                            ("Termination", "Termination"),
                            ("Final Warning", "Final Warning"),
                            ("Demotion", "Demotion"),
                        ],
                        help_text="Type of disciplinary action",
                        max_length=50,
                    ),
                ),
                (
                    "violation_category",
                    models.CharField(
                        choices=[
                            ("Attendance Issues", "Attendance Issues"),
                            ("Misconduct", "Misconduct"),
                            ("Poor Performance", "Poor Performance"),
                            ("Insubordination", "Insubordination"),
                            ("Dishonesty", "Dishonesty"),
                            ("Safety Violation", "Safety Violation"),
                            ("Confidentiality Breach", "Confidentiality Breach"),
                            ("Harassment/Discrimination", "Harassment/Discrimination"),
                            ("Other", "Other"),
                        ],
                        help_text="Category of violation",
                        max_length=100,
                    ),
                ),
                (
                    "violation_title",
                    models.CharField(
                        help_text="Brief title of the violation", max_length=255
                    ),
                ),
                (
                    "violation_description",
                    models.TextField(help_text="Detailed description of the violation"),
                ),
                (
                    "date_of_violation",
                    models.DateField(help_text="Date when the violation occurred"),
                ),
                (
                    "action_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when the action was taken",
                    ),
                ),
                (
                    "investigation_details",
                    models.TextField(
                        blank=True,
                        help_text="Optional investigation details",
                        null=True,
                    ),
                ),
                (
                    "severance_payment_due",
                    models.BooleanField(
                        default=False, help_text="Whether severance payment is due"
                    ),
                ),
                (
                    "severance_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Severance payment amount if applicable",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disciplinary Case",
                "verbose_name_plural": "Disciplinary Cases",
                "db_table": "disciplinary_cases",
                "ordering": ["-date_of_violation", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee_id"], name="disciplinar_employe_6fd5be_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="disciplinar_action__08499c_idx"
                    ),
                    models.Index(
                        fields=["date_of_violation"],
                        name="disciplinar_date_of_1ba10a_idx",
                    ),
                    models.Index(
                        fields=["action_date"], name="disciplinar_action__3b802f_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="disciplinar_created_84d642_idx"
                    ),
                ],
            },
        ),
    ]
