# Generated by Django 5.2.6 on 2026-01-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0020_disciplinarycase"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Associate",
        ),
    ]
