# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import department_service_pb2 as department__service__pb2
from . import department_service_pb2 as department__service__pb2 


GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in department_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DepartmentServiceStub(object):
    """Department Service for validating and fetching department data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateDepartment = channel.unary_unary(
                '/department.DepartmentService/ValidateDepartment',
                request_serializer=department__service__pb2.ValidateDepartmentRequest.SerializeToString,
                response_deserializer=department__service__pb2.ValidateDepartmentResponse.FromString,
                _registered_method=True)
        self.GetDepartment = channel.unary_unary(
                '/department.DepartmentService/GetDepartment',
                request_serializer=department__service__pb2.GetDepartmentRequest.SerializeToString,
                response_deserializer=department__service__pb2.Department.FromString,
                _registered_method=True)
        self.GetDepartments = channel.unary_unary(
                '/department.DepartmentService/GetDepartments',
                request_serializer=department__service__pb2.GetDepartmentsRequest.SerializeToString,
                response_deserializer=department__service__pb2.GetDepartmentsResponse.FromString,
                _registered_method=True)
        self.ValidateSubDepartment = channel.unary_unary(
                '/department.DepartmentService/ValidateSubDepartment',
                request_serializer=department__service__pb2.ValidateSubDepartmentRequest.SerializeToString,
                response_deserializer=department__service__pb2.ValidateSubDepartmentResponse.FromString,
                _registered_method=True)
        self.GetSubDepartment = channel.unary_unary(
                '/department.DepartmentService/GetSubDepartment',
                request_serializer=department__service__pb2.GetSubDepartmentRequest.SerializeToString,
                response_deserializer=department__service__pb2.SubDepartment.FromString,
                _registered_method=True)


class DepartmentServiceServicer(object):
    """Department Service for validating and fetching department data
    """

    def ValidateDepartment(self, request, context):
        """Validate if a department exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepartment(self, request, context):
        """Get department details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDepartments(self, request, context):
        """Get multiple departments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSubDepartment(self, request, context):
        """Validate if a sub-department exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubDepartment(self, request, context):
        """Get sub-department details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DepartmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateDepartment,
                    request_deserializer=department__service__pb2.ValidateDepartmentRequest.FromString,
                    response_serializer=department__service__pb2.ValidateDepartmentResponse.SerializeToString,
            ),
            'GetDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepartment,
                    request_deserializer=department__service__pb2.GetDepartmentRequest.FromString,
                    response_serializer=department__service__pb2.Department.SerializeToString,
            ),
            'GetDepartments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDepartments,
                    request_deserializer=department__service__pb2.GetDepartmentsRequest.FromString,
                    response_serializer=department__service__pb2.GetDepartmentsResponse.SerializeToString,
            ),
            'ValidateSubDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSubDepartment,
                    request_deserializer=department__service__pb2.ValidateSubDepartmentRequest.FromString,
                    response_serializer=department__service__pb2.ValidateSubDepartmentResponse.SerializeToString,
            ),
            'GetSubDepartment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubDepartment,
                    request_deserializer=department__service__pb2.GetSubDepartmentRequest.FromString,
                    response_serializer=department__service__pb2.SubDepartment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'department.DepartmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('department.DepartmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DepartmentService(object):
    """Department Service for validating and fetching department data
    """

    @staticmethod
    def ValidateDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/department.DepartmentService/ValidateDepartment',
            department__service__pb2.ValidateDepartmentRequest.SerializeToString,
            department__service__pb2.ValidateDepartmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/department.DepartmentService/GetDepartment',
            department__service__pb2.GetDepartmentRequest.SerializeToString,
            department__service__pb2.Department.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDepartments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/department.DepartmentService/GetDepartments',
            department__service__pb2.GetDepartmentsRequest.SerializeToString,
            department__service__pb2.GetDepartmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSubDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/department.DepartmentService/ValidateSubDepartment',
            department__service__pb2.ValidateSubDepartmentRequest.SerializeToString,
            department__service__pb2.ValidateSubDepartmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubDepartment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/department.DepartmentService/GetSubDepartment',
            department__service__pb2.GetSubDepartmentRequest.SerializeToString,
            department__service__pb2.SubDepartment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
